server:
  port: 8888
spring:
  application:
    name: im-server
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:127.0.0.1:33060}/gylang-im?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    password: ${REDIS_PWD:123456}
  profiles:
    active: gim
# im




mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:*/mappers/**/*.xml
  type-aliases-package: com.gylang.gim.web.entity

logging:
  level:
    root: debug