gim:
  #  web 服务
  admin-user:
    webAdmin:
      userId: -2
      password: 123456
      name: web推送
    #      数据中心
    datacenter:
      password: 123456
      name: 数据中心
      userId: -3
      loginEvent: true
      persistence: true