server:
  port: 8888

spring:
  application:
    name: im-server

# im
gylang:
  netty:
    serverIp: 127.0.0.1
    bossGroup: 4
    workerGroup: 12
    readerIdle: 10
    writeIdle: 10
    allIdle: 10
    lostConnectRetryNum: 10
    socketServerPort: 46000
    nonAuthCmd:
      - LNST  #客户端接入
    socketType:
      com.gylang.netty.sdk.initializer.WebSocketJsonInitializer: 46000
      com.gylang.netty.sdk.initializer.AppSocketJsonInitializer: 46001

logging:
  level:
    root: debug